### post auth/register
POST http://localhost:3210/auth/register
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "123456"
}
### post auth/login
POST http://localhost:3210/auth/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "123456"
}
### get users
GET http://localhost:3210/api/users
Authorization: Bearer {{token}}

### put api/users/:id
PUT http://localhost:3210/api/users/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "tessssss123"
}
### delete api/users/:id
DELETE http://localhost:3210/api/users/4
Authorization: Bearer {{token}}

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJpYXQiOjE3MzQ3MDM0NTQsImV4cCI6MTczNDc4OTg1NH0.sNAP5t2aB7VjBPoh8gYqerxE6r9njTKrIblh_q1X9L0
